apiVersion: apps/v1
kind: Deployment
metadata:
  name: foliage-proxy
  namespace: foliage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: foliage-proxy
  template:
    metadata:
      labels:
        app: foliage-proxy
    spec:
      containers:
      - name: foliage-proxy
        image: "ghcr.io/foliagecp/proxy:v0.1.3"
        imagePullPolicy: Always
        ports:
        - containerPort: 8801
        livenessProbe:
          tcpSocket:
            port: 8801
        env:
         - name: CMDB_ADDR
           value: "foliage-cmdb"
         - name: CMDB_PORT
           value: "31415"
