apiVersion: apps/v1
kind: Deployment
metadata:
  name: foliage-taskmanager
  namespace: foliage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: statefun
      component: worker
  template:
    metadata:
      labels:
        app: statefun
        component: worker
    spec:
      containers:
        - name: worker
          image: ghcr.io/foliagecp/foliage:0.1.0
          imagePullPolicy: Always
          volumeMounts:
            - name: state
              mountPath: /shared
            - name: log
              mountPath: /opt/flink/log/
          env:
            - name: ROLE
              value: worker
            - name: MASTER_HOST
              value: foliage-jobmanager
            - name: KAFKA_ADDR
              value: kafka-cluster-kafka-brokers:9092
            - name: CMDB_ADDR
              value: "foliage-cmdb"
            - name: CMDB_PORT
              value: "31415"
          ports:
            - containerPort: 6122
              name: rpc
            - containerPort: 6121
              name: blob
          resources:
            requests:
              memory: "1.5Gi"
      volumes:
        - name: state
          persistentVolumeClaim:
            claimName: foliage-taskmanager-state
        - name: log
          persistentVolumeClaim:
            claimName: foliage-taskmanager-log
