apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foliage-jobmanager-state
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: foliage-jobmanager-log
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 0.5Gi
